import pandas as pd
import joblib
import numpy as np

def predict_yield():
    try:
        # Load the model and scaler
        # Note: These files need to be generated by running the last cell in yield.ipynb
        model = joblib.load("yield_model.pkl")
        scaler = joblib.load("scaler.pkl")
        print("Model and Scaler loaded successfully!")
    except FileNotFoundError:
        print("Error: Model files not found. Please run the notebook to train and save the model.")
        return

    # User Input
    print("\n--- Crop Yield Prediction ---")
    year = int(input("Enter Year: "))
    rain = float(input("Enter Average Rainfall (mm/year): "))
    pesticides = float(input("Enter Pesticides (tonnes): "))
    temp = float(input("Enter Average Temperature: "))
    crop = input("Enter Crop (Maize, Potatoes, Rice, Wheat, Sorghum, Soybeans, Sweet potatoes, Yams, Plantains): ").lower()

    # One-Hot Encoding setup
    crop_dict = {
        'Item_Maize': 0,
        'Item_Plantains and others': 0,
        'Item_Potatoes': 0,
        'Item_Rice, paddy': 0,
        'Item_Sorghum': 0,
        'Item_Soybeans': 0,
        'Item_Sweet potatoes': 0,
        'Item_Wheat': 0,
        'Item_Yams': 0
    }

    crop_map = {
        "maize": 'Item_Maize',
        "potatoes": 'Item_Potatoes',
        "rice": 'Item_Rice, paddy',
        "wheat": 'Item_Wheat',
        "sorghum": 'Item_Sorghum',
        "soybeans": 'Item_Soybeans',
        "sweet potatoes": 'Item_Sweet potatoes',
        "yams": 'Item_Yams',
        "plantains": 'Item_Plantains and others'
    }

    if crop in crop_map:
        crop_dict[crop_map[crop]] = 1
    else:
        print("Invalid crop! Predicting with default values.")

    # Create input data structure
    # Match the order of columns used during training
    input_data = [[
        year,
        rain,
        pesticides,
        temp,
        *crop_dict.values()
    ]]

    # Column names for the DataFrame
    columns = [
        'Year', 'average_rain_fall_mm_per_year', 'pesticides_tonnes', 'avg_temp',
        'Item_Maize', 'Item_Plantains and others', 'Item_Potatoes', 'Item_Rice, paddy',
        'Item_Sorghum', 'Item_Soybeans', 'Item_Sweet potatoes', 'Item_Wheat', 'Item_Yams'
    ]

    input_df = pd.DataFrame(input_data, columns=columns)

    # Scale the input if needed (The notebook fits on X_train, but Random Forest doesn't strictly need scaling)
    # However, to be consistent with the training process:
    # input_scaled = scaler.transform(input_df) 
    
    # Predict
    prediction = model.predict(input_df)

    print("\n" + "="*30)
    print(f"🌾 Predicted Crop Yield: {prediction[0]:.2f} hg/ha")
    print("="*30)

if __name__ == "__main__":
    predict_yield()
